spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
    
  mvc:
    hiddenmethod:
      filter:
        enabled: true
        
  h2.console.enabled: true
  

    
   


