CREATE TABLE board
(
   id INT NOT NULL AUTO_INCREMENT,
   title VARCHAR(100) NOT NULL,
   name VARCHAR(100) NOT NULL,
   text VARCHAR(1000) NOT NULL,
   created DATETIME NOT NULL,
   PRIMARY KEY(id)
);
